name: Rust

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: x86_64-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v1

      - name: Install nightly clippy
        run: rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Lint
        run: cargo +nightly clippy --lib -- -D warnings

  lint-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v1
      - uses: jetli/wasm-pack-action@v0.3.0

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown && rustup override set nightly && rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Lint (wasm32)
        run: cargo +nightly check --target wasm32-unknown-unknown --lib

  isomorphic:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: x86_64-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v1

      - name: Test
        run: cargo +nightly test -- --nocapture
        env:
          TEST_WALLET_SEED: ${{ secrets.TEST_WALLET_SEED }}
          RUST_BACKTRACE: 1

  web:
    runs-on: ubuntu-latest
    needs: lint-wasm

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v1
      - uses: jetli/wasm-pack-action@v0.3.0

      - name: Add wasm32 target
        run: rustup override set nightly && rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Test
        run: wasm-pack test --headless --chrome
        env:
          TEST_WALLET_SEED: ${{ secrets.TEST_WALLET_SEED }}
